"""tablas iniciales

Revision ID: 3b7e8d29361d
Revises: 9ac397bdf3ed
Create Date: 2026-06-07 17:51:58.481272
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# Identificadores de la revisión, usados por Alembic.
revision: str = '3b7e8d29361d'
down_revision: Union[str, None] = '9ac397bdf3ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
