"""tablas iniciales

Revision ID: fb740aec4af9
Revises: 34a4cc083f55
Create Date: 2026-06-07 17:33:14.203398
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# Identificadores de la revisión, usados por Alembic.
revision: str = 'fb740aec4af9'
down_revision: Union[str, None] = '34a4cc083f55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
