"""tablas iniciales

Revision ID: 8ad80740d355
Revises: 5bc9cbe748b1
Create Date: 2026-06-08 00:08:06.157094
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# Identificadores de la revisión, usados por Alembic.
revision: str = '8ad80740d355'
down_revision: Union[str, None] = '5bc9cbe748b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
