"""tablas iniciales

Revision ID: 9ac397bdf3ed
Revises: fb740aec4af9
Create Date: 2026-06-07 17:43:45.460608
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# Identificadores de la revisión, usados por Alembic.
revision: str = '9ac397bdf3ed'
down_revision: Union[str, None] = 'fb740aec4af9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
