"""tablas iniciales

Revision ID: e7659ebc5e32
Revises: f50e872e31a4
Create Date: 2026-06-07 23:35:21.049438
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# Identificadores de la revisión, usados por Alembic.
revision: str = 'e7659ebc5e32'
down_revision: Union[str, None] = 'f50e872e31a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
