"""tablas iniciales

Revision ID: f50e872e31a4
Revises: 851440199f9d
Create Date: 2026-06-07 20:27:07.076161
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# Identificadores de la revisión, usados por Alembic.
revision: str = 'f50e872e31a4'
down_revision: Union[str, None] = '851440199f9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_alineacion_partido_jugador', 'alineaciones', ['partido_id', 'jugador_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_alineacion_partido_jugador', 'alineaciones', type_='unique')
    # ### end Alembic commands ###
