"""tablas iniciales

Revision ID: 5bc9cbe748b1
Revises: e7659ebc5e32
Create Date: 2026-06-08 00:02:56.642980
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# Identificadores de la revisión, usados por Alembic.
revision: str = '5bc9cbe748b1'
down_revision: Union[str, None] = 'e7659ebc5e32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
